### ISSUE TITLE
Release new flow layers in upthat releases

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/upthat#21]
- [ ] New Demo City with tiny size but same structure for testing

- [ ] Kathmandu
- [ ] NYC 
- [ ] Bristol

**Comment by mpadge** [comment]
First full cuts for Accra and Kathmandu now [uploaded](https://github.com/ATFutures/upthat/releases/tag/0.0.2). All works perfectly on my local instance, so hopefully should auto-work on public server. We need to also think about how to incorporate tests with data releases to ensure any changes there will actually work? Anyway, it should just work with demo data for Kathmandu only until release data have been downloaded to local `inst`, after which Kathmandu should be automatically updated to the full analysis. There is thus no need for "Demo" in the above list, yet we still retain the "demo" functionality in the absence of any additional data, which is (i think) nice.

---

Edit: This issue is not quite ready to close, because i still need to properly scale Kathmandu to local data, and also to include NYC. But most importantly, i need address #22 first, which includes embedding a few scaling parameters as `attributes` of each `net-<city>.Rds` file. I've done that for Accra and Kathmandu, but not yet enabled the use of those parameters for scenario switching.

**Comment by Robinlovelace** [comment]
Great work @mpadge, should have checked before chatting, will test here asap.

**Comment by Robinlovelace** [comment]
Heads-up @mpadge I just tested the new version of the data on the current branch and works good, Accra shown below.

![image](https://user-images.githubusercontent.com/1825120/69529868-fc2c5280-0f68-11ea-8905-10e3dc805f64.png)

**Comment by Robinlovelace** [comment]
Just testing with latest PR. One issue: the lines still rather faint and thin. But great to see it working well for Accra :+1: 

![image](https://user-images.githubusercontent.com/1825120/69530235-98eef000-0f69-11ea-8ef1-c9814a46f505.png)

**Comment by Robinlovelace** [comment]
@mpadge could you update the demo data in the `inst` folder?

**Comment by Robinlovelace** [comment]
Also looks good for Kathmandu as shown below. But it's not clear what the units are: I would expect more than 700 pedestrians to pass the busiest streets in the city (and more than 255 in Accra).

![image](https://user-images.githubusercontent.com/1825120/69530582-2b8f8f00-0f6a-11ea-8bf2-f070f36e3773.png)

**Comment by mpadge** [comment]
@Robinlovelace We need to decide here which layers we are going to keep, and which not. As it really is MVP, my first suggestion would be just the main 2. Thoughts?

**Comment by Robinlovelace** [comment]
We said we'd release additional cities compared with Phase II. Can you share the code used to build the latest flow layers? From that it should be easy to build data for Bristol and NY (at a minimum).

**Comment by mpadge** [comment]
NY can do, but Bristol is actually really tricky without knowing aggregate passenger numbers at Temple Meads (and other suburban stations). Bristol's PT is too multi-modal for NY model to translate directly absent a bit of additional calibration info

**Comment by Robinlovelace** [comment]
Doesn't need to be accurate, just a proof of concept.
