### ISSUE TITLE
Issues with new health tab

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/upthat#38]
Quick one: the results in the new health tab (which overall look great btw!) should I think:

- [ ] Respond to changes in the case study city made on the interactive map
- [x] Not duplicate the dropdown menu in the map tab
- [x] Currently returns error message

Thoughts @mpadge ? See below a GIF that highlights the impact of these issues for the user:

![Peek 2019-11-29 16-12](https://user-images.githubusercontent.com/1825120/69881040-9c64dd00-12c3-11ea-9dcc-05278d256895.gif)

**Comment by mpadge** [comment]
Entirely possible to make them reflect city chosen in main map - that definitely requires changing all to `react`, but that is now very straightforward

**Comment by Robinlovelace** [comment]
Great, you up for giving it a bash? I think most shiny functions are inherently reactive but likely I'm missing something. You up for giving this one a bash?

**Comment by mpadge** [comment]
This can be closed now, right @Robinlovelace? If so, please do

**Comment by Robinlovelace** [comment]
I don't think so. On the released version I currently see this (which has the unwanted city selector dropdown and for some reason generates an error):

![image](https://user-images.githubusercontent.com/1825120/70343208-94bab080-184e-11ea-907b-f35c52e6b5fc.png)


Maybe when the latest PR is merged it can be closed but suggest we only close issues when they are fixed on the public facing deployment. Sound reasonable?

**Comment by Robinlovelace** [comment]
Heads-up @mpadge here's a reproducible example of the health tab crashing, with this message: `EXPR must be a length 1 vector`.

Please try to reproduce + fix if easy, we could remove the tab if not.

```r
devtools::install_github("atfutures/upthat")
upthat::runUpthat()
```

**Comment by mpadge** [comment]
Shall do - thanks

**Comment by thiagoherickdesa** [comment]
Thanks for sharing this link, Robin. 

- Also noticed that choosing Bristol or NYC from the dropdown menu disconnects the tool form the server. 
- Choosing Accra and Kathmandu should zoom in closer (even after clicking on the buttom zoom in to city extent), otherwise the user has to do it himself. 
- Vehicular flow: all motorized vehicles? Tuc-tucs and motorbikes as well? Description should be somewhere easy for user to find
- Vehicular emissions: PM2.5? Which method is being used to model that, Vara-Vela et al.? Average weekly emissions?
- Pedestrian exposure: to PM2.5? Average weekly exposure? Which methods have been used for that?

The tool is looking great but, at the moment, it should provide more details on some of these methodological decisions not only in the supporting articles but also on the tool visualisation itself (e.g. through pop-up descriptions).

**Comment by mpadge** [comment]
Thanks @thiagoherickdesa, some initial responses:

> choosing Bristol or NYC from the dropdown menu disconnects the tool form the server

NYC is up and works, but the data are so enormous that we don't have them on the server, and may not do so, because they will likely cause local issues unless people have sufficiently powerful computers. We'd like to discuss this with you.

> Choosing Accra and Kathmandu should zoom in closer (even after clicking on the buttom zoom in to city extent), otherwise the user has to do it himself.

Agreed, but this is an issue that is currently beyond our own hands (see #31), and is caused by the underlying map technology we use, which is in turn developed by Uber. It basically comes down to waiting for them to fix it, which they always do, and generally do so very quickly.

> Vehicular flow: all motorized vehicles? Tuc-tucs and motorbikes as well? Description should be somewhere easy for user to find

At present, just motorcars as proof of principle. Incorporating separate layer for motorbikes is now very straightforward, and will be done asap. Note, however, that that requires city-specific estimates of relative numbers of trips, which we have for Accra, but nowhere else yet.

> Vehicular emissions: PM2.5? Which method is being used to model that, Vara-Vela et al.? Average weekly emissions?

Not Vara-Vela, rather a realistic model of dynamic vehicle movement, along the lines of the science behind the [London Clear Air Walking Routes](https://crossriverpartnership.org/projects/clean-air-walking-routes/). Our models will eventually -- but have not yet been at this stage! -- calibrated against the data used for that system. That will then validate our procedures for emissions calculations.

> Pedestrian exposure: to PM2.5? Average weekly exposure? Which methods have been used for that?

Now briefly described in [Adaptation Manual](https://github.com/ATFutures/who3/tree/master/health-econ), but currently just considered a metric of "relative exposure", because conversion to any absolute units is not straightforward.
